blog/urls.py
from django.urls import path, include

from blog.views import post_list, post_detail, category_list

app_name = 'blog'

urlpatterns = [
    path('', post_list, name='list'),
    path('<int:id>/', post_detail, name='detail'),
    path('category/<int:category_id>/', category_list, name='category_list')
]

blogpy/urls.py
from django.contrib import admin
from django.urls import path, include
from details.views import home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('details.urls', namespace='details')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

details/urls.py
from django.urls import path
from details.views import home, about, contact

app_name = 'details'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Category(models.Model):
    name = models.CharField('نام', max_length=24)
    image = models.ImageField('عکس', upload_to='category')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Tag(models.Model):
    name = models.CharField('تگ', max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'تگ'
        verbose_name_plural = 'تگ ها'


class Post(models.Model):
    STATUS_CHOICE = (
        ('0', 'در انتظار'),
        ('1', 'منتشر شده')
    )
    title = models.CharField('عنوان', max_length=256)
    cover = models.ImageField('کاور', upload_to='post', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='دسته بندی')
    description = models.TextField('متن', blank=True, null=True)
    visit = models.PositiveIntegerField('بازدید ها', default=0)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField()
    status = models.CharField('وضعیت', choices=STATUS_CHOICE, default='0', max_length=20)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده')
    tag = models.ManyToManyField(Tag, verbose_name='تگ')

    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

details/models.py
from django.db import models


class Contact(models.Model):
    full_name = models.CharField('نام و نام خانوادگی', max_length=128)
    phone = models.CharField('شماره تماس', max_length=11, null=True, blank=True)
    email = models.EmailField('ایمیل', null=True, blank=True)
    description = models.TextField('توضیحات')
    created_at = models.DateTimeField('زمان ساخت', auto_now_add=True)

    class Meta:
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'تماس با ما'

    def __str__(self):
        return self.full_name

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Category
# Create your views here.



def sidbar_data(request):
    caregory = Category.objects.all()
    popular_post = Post.objects.filter(status=1).order_by('-visit')[:3]

    context = {
        'caregory': caregory,
        'popular_post': popular_post
    }

    return context


def post_list(request):
    posts = Post.objects.filter(status=1)
    sidbar = sidbar_data(request)

    return  render(request, 'list.html',{'posts': posts, 'sidbar': sidbar})

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    post.visit += 1
    post.save()

    sidbar = sidbar_data(request)

    return render(request, 'detail.html',{'post': post, 'sidbar': sidbar})

def category_list(request, category_id):
    posts = Post.objects.filter(status=1, category=category_id)
    sidbar = sidbar_data(request)
    category = get_object_or_404(Category, id=category_id)
    return  render(request, 'category.html',{'posts': posts, 'sidbar': sidbar, 'category': category})

details/views.py
from django.shortcuts import render
from blog.views import sidbar_data


def home(request):


    sidbar = sidbar_data(request)

    return render(request, 'page/home.html', {'sidbar': sidbar})


def about(request):


    sidbar = sidbar_data(request)

    return render(request, 'page/about.html', {'sidbar': sidbar})


def contact(request):


    sidbar = sidbar_data(request)

    return render(request, 'page/contact.html', {'sidbar': sidbar})

details/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="fa">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>وبلاگ خبری و مجله ای بلاگر || Blogar - قالب وبلاگ شخصی</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon -->
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'assets/images/favicon.png' %}"
    />

    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins/plugins.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  </head>

  <body dir="rtl">
    <div id="preloader">
      <span class="loader"></span>
    </div>
    <div class="main-wrapper">
      <div class="mouse-cursor cursor-outer"></div>
      <div class="mouse-cursor cursor-inner"></div>

      <div id="my_switcher" class="my_switcher">
        <ul>
          <li>
            <a
              href="javascript: void(0);"
              data-theme="light"
              class="setColor light"
            >
              <span title="Light Mode">روشن</span>
            </a>
          </li>
          <li>
            <a
              href="javascript: void(0);"
              data-theme="dark"
              class="setColor dark"
            >
              <span title="Dark Mode">تیره</span>
            </a>
          </li>
        </ul>
      </div>

        {% include 'header.html' %}


        {% block content %} {% endblock content %}


        {% include 'footer.html' %}

      <!-- Start Back To Top  -->
      <a id="backto-top"></a>
      <!-- End Back To Top  -->
    </div>

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static 'assets/js/vendor/modernizr.min.js' %}"></script>
    <!-- jQuery JS -->
    <script src="{% static 'assets/js/vendor/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/tweenmax.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/js.cookie.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.style.switcher.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

details/templates/footer.html
{% load static %}
      <!-- Start Footer Area  -->
      <footer class="axil-footer-area axil-footer-style-1 footer-variation-2">
        <div class="footer-mainmenu">
          <div class="container">
            <div class="row">
              <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-right">
                  <h3 class="title">لینک 1</h3>
                  <div class="inner">
                    <ul class="ft-menu-list">
                      <li><a href="#">لپ تاب</a></li>
                      <li><a href="#">کامپیوتر</a></li>
                      <li><a href="#">نرم افزار</a></li>
                      <li><a href="#">تبلت</a></li>
                      <li><a href="#">دوربین</a></li>
                      <li><a href="#">سیستم عامل</a></li>
                      <li><a href="#">سخت افزار</a></li>
                      <li><a href="#">هوش مصنوعی</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-right">
                  <h3 class="title">لینک 2</h3>
                  <div class="inner">
                    <ul class="ft-menu-list">
                      <li><a href="#">لپ تاب</a></li>
                      <li><a href="#">کامپیوتر</a></li>
                      <li><a href="#">نرم افزار</a></li>
                      <li><a href="#">تبلت</a></li>
                      <li><a href="#">دوربین</a></li>
                      <li><a href="#">سیستم عامل</a></li>
                      <li><a href="#">سخت افزار</a></li>
                      <li><a href="#">هوش مصنوعی</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-right">
                  <h3 class="title">لینک 3</h3>
                  <div class="inner">
                    <ul class="ft-menu-list">
                      <li><a href="#">لپ تاب</a></li>
                      <li><a href="#">کامپیوتر</a></li>
                      <li><a href="#">نرم افزار</a></li>
                      <li><a href="#">تبلت</a></li>
                      <li><a href="#">دوربین</a></li>
                      <li><a href="#">سیستم عامل</a></li>
                      <li><a href="#">سخت افزار</a></li>
                      <li><a href="#">هوش مصنوعی</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-right">
                  <h3 class="title">لینک 4</h3>
                  <div class="inner">
                    <ul class="ft-menu-list">
                      <li><a href="#">لپ تاب</a></li>
                      <li><a href="#">کامپیوتر</a></li>
                      <li><a href="#">نرم افزار</a></li>
                      <li><a href="#">تبلت</a></li>
                      <li><a href="#">دوربین</a></li>
                      <li><a href="#">سیستم عامل</a></li>
                      <li><a href="#">سخت افزار</a></li>
                      <li><a href="#">هوش مصنوعی</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-right">
                  <h3 class="title">لینک 5</h3>
                  <div class="inner">
                    <ul class="ft-menu-list">
                      <li><a href="#">لپ تاب</a></li>
                      <li><a href="#">کامپیوتر</a></li>
                      <li><a href="#">نرم افزار</a></li>
                      <li><a href="#">تبلت</a></li>
                      <li><a href="#">دوربین</a></li>
                      <li><a href="#">سیستم عامل</a></li>
                      <li><a href="#">سخت افزار</a></li>
                      <li><a href="#">هوش مصنوعی</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-right">
                  <h3 class="title">لینک 6</h3>
                  <div class="inner">
                    <ul class="ft-menu-list">
                      <li><a href="#">لپ تاب</a></li>
                      <li><a href="#">کامپیوتر</a></li>
                      <li><a href="#">نرم افزار</a></li>
                      <li><a href="#">تبلت</a></li>
                      <li><a href="#">دوربین</a></li>
                      <li><a href="#">سیستم عامل</a></li>
                      <li><a href="#">سخت افزار</a></li>
                      <li><a href="#">هوش مصنوعی</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Start Footer Top Area  -->
        <div class="footer-top">
          <div class="container">
            <div class="row">
              <div class="col-lg-4 col-md-4">
                <div class="logo text-right">
                  <a href="index.html">
                    <img
                      class="dark-logo"
                      src="{% static 'assets/images/logo/logo-black.png' %}"
                      alt="Logo Images"
                    />
                    <img
                      class="white-logo"
                      src="{% static 'assets/images/logo/logo-white2.png' %}"
                      alt="Logo Images"
                    />
                  </a>
                </div>
              </div>

              <div class="col-lg-8 col-md-8">
                <!-- Start Post List  -->
                <div
                  class="d-flex justify-content-start mt_sm--15 justify-content-md-end align-items-center flex-wrap"
                >
                  <h5 class="follow-title mb--0 mr--20">ما را دنبال کنید</h5>
                  <ul
                    class="social-icon color-tertiary md-size justify-content-start"
                  >
                    <li>
                      <a href="#"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </li>
                  </ul>
                </div>
                <!-- End Post List  -->
              </div>
            </div>
          </div>
        </div>
        <!-- End Footer Top Area  -->

        <!-- Start Copyright Area  -->
        <div class="copyright-area">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-lg-9 col-md-8">
                <div class="copyright-left">
                  <ul class="mainmenu justify-content-start">
                    <li>
                      <a class="hover-flip-item-wrapper" href="#">
                        <span class="hover-flip-item">
                          <span data-text="تماس با ما">تماس با ما</span>
                        </span>
                      </a>
                    </li>
                    <li>
                      <a class="hover-flip-item-wrapper" href="#">
                        <span class="hover-flip-item">
                          <span data-text="شرایط و قوانین">شرایط و قوانین</span>
                        </span>
                      </a>
                    </li>
                    <li>
                      <a class="hover-flip-item-wrapper" href="#">
                        <span class="hover-flip-item">
                          <span data-text="درباره ما">درباره ما</span>
                        </span>
                      </a>
                    </li>
                    <li>
                      <a class="hover-flip-item-wrapper" href="#">
                        <span class="hover-flip-item">
                          <span data-text="تبلیغات با ما">تبلیغات با ما</span>
                        </span>
                      </a>
                    </li>
                    <li>
                      <a class="hover-flip-item-wrapper" href="#">
                        <span class="hover-flip-item">
                          <span data-text="لیست مقالات">لیست مقالات</span>
                        </span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-3 col-md-4">
                <div
                  class="copyright-right text-end text-lg-start mt_md--20 mt_sm--20"
                >
                  <p class="b3">© کلیه حقوق این سایت محفوظ می باشد</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- End Copyright Area  -->
      </footer>
      <!-- End Footer Area  -->

details/templates/header.html
{% load static %}
      <!-- Start Header -->
      <header class="header axil-header header-light header-sticky header-with-shadow">
        <div class="header-wrap">
          <div class="row justify-content-between align-items-center">
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-3 col-9">
              <div class="logo text-right mb-sm-0">
                <a href="{% url 'details:home' %}">
                  <img
                    class="dark-logo"
                    src="{% static 'assets/images/logo/logo-black.png' %}"
                    alt="Blogar logo"
                  />
                  <img
                    class="light-logo"
                    src="{% static 'assets/images/logo/logo-white2.png' %}"
                    alt="Blogar logo"
                  />
                </a>
              </div>
            </div>

            <div class="col-xl-6 d-none d-xl-block">
              <div class="mainmenu-wrapper">
                <nav class="mainmenu-nav">
                  <!-- Start Mainmanu Nav -->
                  <ul class="mainmenu">
                    <li>
                      <a href="{% url 'details:home' %}">خانه</a>
                    </li>
                    <li class="menu-item-has-children">
                      <a href="#">دسته بندی</a>
                      <ul class="axil-submenu">
                          {% for item in sidbar.category %}
                        <li>
                          <a class="hover-flip-item-wrapper" href="{% url 'blog:list'%}">
                            <span class="hover-flip-item">
                              <span data-text="همه">همه</span>
                            </span>
                          </a>
                        </li>
                          {% endfor %}
                      </ul>
                    </li>
                    <li>
                      <a href="{% url 'details:contact' %}">تماس با ما</a>
                    </li>
                    <li><a href="{% url 'details:about' %}">درباره ما</a></li>
                  </ul>
                  <!-- End Mainmanu Nav -->
                </nav>
              </div>
            </div>

            <div class="col-xl-3 col-lg-8 col-md-8 col-sm-9 col-3 text-st">
                <!-- Start Hamburger Menu  -->
                <div class="hamburger-menu d-block d-xl-none">
                  <div class="hamburger-inner">
                    <div class="icon"><i class="fal fa-bars"></i></div>
                  </div>
                </div>
                <!-- End Hamburger Menu  -->
              </div>
            </div>
          </div>
        </div>
      </header>
      <!-- Start Header -->

      <!-- Start Mobile Menu Area  -->
      <div class="popup-mobilemenu-area">
        <div class="inner">
          <div class="mobile-menu-top">
            <div class="logo">
              <a href="index.html">
                <img
                  class="dark-logo"
                  src="{% static 'assets/images/logo/logo-black.png' %}"
                  alt="Logo Images"
                />
                <img
                  class="light-logo"
                  src="{% static 'assets/images/logo/logo-white2.png' %}"
                  alt="Logo Images"
                />
              </a>
            </div>
            <div class="mobile-close">
              <div class="icon">
                <i class="fal fa-times"></i>
              </div>
            </div>
          </div>
          <ul class="mainmenu">
            <li><a href="index.html">خانه</a></li>
            <li class="menu-item-has-children">
              <a href="#">دسته بندی ها</a>
              <ul class="axil-submenu">
                <li><a href="post-details.html">فرهنگ و هنر</a></li>
                <li><a href="post-details.html">فناوری اطلاعات</a></li>
                <li><a href="post-details.html">ورزشی</a></li>
                <li><a href="post-details.html">نرم افزارهای کاربردی</a></li>
              </ul>
            </li>

            <li><a href="about.html">درباره ما</a></li>
            <li><a href="contact.html">تماس با ما</a></li>
          </ul>
        </div>
      </div>
      <!-- End Mobile Menu Area  -->

details/templates/page/about.html
{% extends 'base.html' %}{% block content %}
{% load static jalali_tags %}
<!-- Start Banner Area  -->
      <div class="axil-banner banner-style-1 bg_image bg_image--1">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="inner text-right">
                <h1 class="title">درباره ما</h1>
                <p class="description">
                  هر جا که به ما نیاز داشتی ما اینجا برای شما هستیم - برای تمام
                  نیازهای پشتیبانی خود با ما تماس بگیرید.<br />
                  چه فنی، چه سوالات عمومی یا پشتیبانی اطلاعاتی.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- End Banner Area  -->

      <!-- Start Post List Wrapper  -->
      <div class="axil-post-list-area axil-section-gap bg-color-white">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-xl-8">
              <!-- Start About Area  -->
              <div class="axil-about-us">
                <div class="inner text-justify">
                  <h3>پلتفرم انتشارات حرفه ای</h3>
                  <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و
                    با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه
                    و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی
                    تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای
                    کاربردی می باشد.
                  </p>
                  <p>
                    کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت
                    فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت
                    بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و
                    فرهنگ پیشرو در زبان فارسی ایجاد کرد.
                  </p>
                  <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و
                    با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه
                    و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی
                    تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای
                    کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و
                    آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم
                    افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص
                    طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این
                    صورت می توان امید داشت که تمام و دشواری موجود در ارائه
                    راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل
                    حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای
                    موجود طراحی اساسا مورد استفاده قرار گیرد.
                  </p>
                  <h3>شبکه خبری در حال رشد ما</h3>
                  <p>
                    سیسرو به طور مشهور علیه حریف سیاسی خود لوسیوس سرگیوس
                    کاتیلینا سخنرانی کرد. گاهی اوقات اولین سخنرانی علیه کاتیلین
                    برای نمونه‌های نوع گرفته می‌شود: Quo usque tandem abutere,
                    Catilina, paticia nostra? Quam diu etiam furor iste tuus nos
                    eludet؟ (ای کاتلین، تا کی از صبر ما سوء استفاده می کنی؟ و
                    این دیوانگی تو تا کی ما را مسخره می کند؟)
                  </p>
                  <p>
                    اکثر ویرایشگرهای متن مانند MS Word یا Lotus Notes متن تصادفی
                    لورم را در صورت نیاز تولید می کنند، چه به عنوان ماژول از پیش
                    نصب شده یا افزونه برای اضافه شدن. انتخاب کلمه یا دنباله
                    لزوماً با اصل مطابقت ندارد، که برای ایجاد تنوع در نظر گرفته
                    شده است.
                  </p>
                  <h3>پلتفرم انتشارات حرفه ای</h3>
                  <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و
                    با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه
                    و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی
                    تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای
                    کاربردی می باشد.
                  </p>
                  <p>
                    کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت
                    فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت
                    بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و
                    فرهنگ پیشرو در زبان فارسی ایجاد کرد.
                  </p>
                  <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و
                    با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه
                    و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی
                    تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای
                    کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و
                    آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم
                    افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص
                    طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این
                    صورت می توان امید داشت که تمام و دشواری موجود در ارائه
                    راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل
                    حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای
                    موجود طراحی اساسا مورد استفاده قرار گیرد.
                  </p>
                </div>
              </div>
              <!-- End About Area  -->
            </div>
            <div class="col-lg-4 col-xl-4 mt_md--40 mt_sm--40">
              <!-- Start Sidebar Area  -->
              {% include 'sidbar.html' %}
            </div>
          </div>
        </div>
      </div>
      <!-- End Post List Wrapper  -->
{% endblock content %}

details/templates/sidbar.html
              {% load static jalali_tags %}
              <!-- Start Sidebar Area  -->
              <div class="sidebar-inner">
                <!-- Start Single Widget  -->
                <div class="axil-single-widget widget widget_categories mb--30">
                  <ul>
                      {% for category in sidbar.category %}
                    <li class="cat-item">
                      <a href="#" class="inner">
                        <div class="thumbnail">
                          <img
                            src="{{ category.image.url }}"
                            alt=""
                          />
                        </div>
                        <div class="content">
                          <h6 class="title">{{ category.name }}</h6>
                        </div>
                      </a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
                <!-- End Single Widget  -->

                <!-- Start Single Widget  -->
                <div class="axil-single-widget widget widget_search mb--30">
                  <h5 class="widget-title">جستجو</h5>
                  <form action="#">
                    <div class="axil-search form-group">
                      <button type="submit" class="search-button">
                        <i class="fal fa-search"></i>
                      </button>
                      <input
                        type="text"
                        class="form-control"
                        placeholder="جستجو"
                      />
                    </div>
                  </form>
                </div>
                <!-- End Single Widget  -->

                <!-- Start Single Widget  -->
                <div class="axil-single-widget widget widget_postlist mb--30">
                  <h5 class="widget-title">بهترین ها</h5>
                  <!-- Start Post List  -->
                  <div class="post-medium-block">
                    <!-- Start Single Post  -->
                      {% for item in sidbar.popular_post %}
                    <div class="content-block post-medium mb--20">
                      <div class="post-thumbnail">
                        <a href="{% url 'blog:detail' item.id %}">
                          <img
                            src="{{ item.cover.url }}"
                            alt="Post Images"
                          />
                        </a>
                      </div>
                      <div class="post-content">
                        <h6 class="title">
                          <a href="{% url 'blog:detail' item.id %}"
                            >{{ item.title }}
                          </a>
                        </h6>
                        <div class="post-meta">
                          <ul class="post-meta-list">
                            <li>{{ item.created_at|to_jalali:'%Y/%m/%d' }}</li>
                            <li>{{ item.visit }} نفر بازدید</li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <!-- End Single Post  -->
                      {% endfor %}
                  </div>
                  <!-- End Post List  -->
                </div>
                <!-- End Single Widget  -->

                <!-- Start Single Widget  -->
                <div class="axil-single-widget widget widget_social mb--30">
                  <h5 class="widget-title">شبکه های اجتماعی ما</h5>
                  <!-- Start Post List  -->
                  <ul class="social-icon md-size justify-content-center">
                    <li>
                      <a href="#"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-slack"></i></a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </li>
                  </ul>
                  <!-- End Post List  -->
                </div>
                <!-- End Single Widget  -->
              </div>
              <!-- End Sidebar Area  -->